/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_com_android_serialport_SerialPort
#define _Included_com_android_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
 JNIEXPORT jobject JNICALL Java_me_f1reking_serialportlib_SerialPortHelper_nativeOpen
        (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
 JNIEXPORT void JNICALL Java_me_f1reking_serialportlib_SerialPortHelper_nativeClose
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
